#cloud-config
autoinstall:
  version: 1

  locale: en_GB
  keyboard:
    layout: gb

  identity:
    hostname: jelly-Ideapad
    username: jelly
    password: "1212"

  timezone: Europe/London

  storage:
    layout:
      name: direct   # Wipes the entire disk automatically

  drivers:
    install: true    # Installs third-party drivers (graphics, Wi-Fi, etc.)

  packages:
    - python3
    - python3-pip
    - python3-venv
    - git
    - curl
    - wget
    - neofetch

  apt:
    preserve_sources_list: false
    primary:
      - arches: [amd64]
        uri: http://archive.ubuntu.com/ubuntu

  late-commands:
    # ✅ Update & upgrade
    - curtin in-target --target=/target -- bash -c "apt update && apt upgrade -y"

    # ✅ Write Git config directly (avoids $HOME errors)
    - curtin in-target --target=/target -- bash -c "echo '[user]\n    name = Cristian Predescu\n    email = cristipredescu21@yahoo.com\n[init]\n    defaultBranch = main\n[credential]\n    helper = store' > /home/jelly/.gitconfig && chown jelly:jelly /home/jelly/.gitconfig"

    # ✅ Download VS Code, Discord, Steam into Downloads
    - curtin in-target --target=/target -- bash -c "mkdir -p /home/jelly/Downloads && cd /home/jelly/Downloads && wget -O code.deb https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64 && wget -O discord.deb https://stable.dl2.discordapp.net/apps/linux/0.0.102/discord-0.0.102.deb && wget -O steam.deb https://cdn.fastly.steamstatic.com/client/installer/steam.deb && chown jelly:jelly /home/jelly/Downloads/*"

    # ✅ Install the .deb files
    - curtin in-target --target=/target -- bash -c "apt install -y /home/jelly/Downloads/code.deb /home/jelly/Downloads/discord.deb /home/jelly/Downloads/steam.deb"

    # ✅ Download wallpaper to Documents
    - curtin in-target --target=/target -- bash -c "mkdir -p /home/jelly/Documents && wget -O /home/jelly/Documents/NoGameNoLife.png https://github.com/cristian-predescu-22/VS/blob/main/NoGameNoLife.png?raw=true && chown jelly:jelly /home/jelly/Documents/NoGameNoLife.png"

    # ✅ Create ChatGPT shortcut + icon
    - curtin in-target --target=/target -- bash -c "mkdir -p /home/jelly/.local/share/applications /home/jelly/.local/share/icons"
    - curtin in-target --target=/target -- bash -c "wget -O /home/jelly/.local/share/icons/chatgpt.png https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg && chown jelly:jelly /home/jelly/.local/share/icons/chatgpt.png"
    - curtin in-target --target=/target -- bash -c \"echo '[Desktop Entry]\nName=ChatGPT\nComment=Open ChatGPT in your browser\nExec=firefox https://chat.openai.com/\nIcon=/home/jelly/.local/share/icons/chatgpt.png\nTerminal=false\nType=Application\nCategories=Utility;AI;\nStartupNotify=true' > /home/jelly/.local/share/applications/chatgpt.desktop && chown jelly:jelly /home/jelly/.local/share/applications/chatgpt.desktop"

    # ✅ Configure Neofetch
    - curtin in-target --target=/target -- bash -c "mkdir -p /home/jelly/.config/neofetch && chown jelly:jelly /home/jelly/.config/neofetch"
    - curtin in-target --target=/target -- bash -c \"echo 'print_info() {\n    info title\n    info underline\n    info \"OS\" distro\n    info \"Kernel\" kernel\n    info \"Uptime\" uptime\n    info \"Resolution\" resolution\n    info \"DE\" de\n    info \"WM\" wm\n    info \"CPU\" cpu\n    info \"GPU\" gpu\n    info \"Memory\" memory\n    info \"Battery\" battery\n    info \"Shell\" shell\n    info \"Theme\" theme\n    info \"Terminal\" term\n    info cols\n}' > /home/jelly/.config/neofetch/config.conf && chown jelly:jelly /home/jelly/.config/neofetch/config.conf"
